---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      terminationGracePeriodSeconds: 4
      tolerations:
      nodeSelector:
      containers:
      - name: cartservice
        image: quay.io/phagen/cartserviceprofiling:3.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 7070
        env:
        - name: REDIS_ADDR
          value: "redis-cart:6379"
        - name: PORT
          value: "7070"
        - name: LISTEN_ADDR
          value: "0.0.0.0"
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: SIGNALFX_ENDPOINT_URL
          value: "http://$(NODE_IP):9411/api/v2/spans"
        - name: SIGNALFX_METRICS_ENDPOINT_URL
          value: "http://$(NODE_IP):9943/v2/datapoint"
        - name: SIGNALFX_PROFILER_ENABLED
          value: "true"
        - name: SIGNALFX_PROFILER_LOGS_ENDPOINT
          value: "http://$(NODE_IP):4318/v1/logs"
        - name: SIGNALFX_PROFILER_CALL_STACK_INTERVAL
          value: "1000"
        - name: SIGNALFX_RUNTIME_METRICS_ENABLED
          value: "true"
        - name: SIGNALFX_SERVICE_NAME
          value: "cartservice"
        - name: SIGNALFX_ENV
          value: "demo"
        - name: EXTERNAL_DB_NAME
          value: 'external-DB
        - name: EXTERNAL_DB_ACCESS_RATE
          value: "0.75"
        - name: EXTERNAL_DB_MAX_DURATION_MILLIS
          value: "750"
        - name: EXTERNAL_DB_ERROR_RATE
          value: "0.0"
        - name: FIX_EXCESSIVE_ALLOCATION
          value: "true"
        - name: FIX_SLOW_LEAK
          value: "true"
        - name: OPTIMIZE_CPU
          value: "true"
        - name: OPTIMIZE_BLOCKING
          value: "true"
        - name:  SCAN_REDIS_ERROR
          value: "true" 
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 300m
            memory: 158Mi
        readinessProbe:
          initialDelaySeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
  - name: grpc
    port: 7070
    targetPort: 7070